cpp_files := main.cpp \

public_headers :=

qt_headers :=

moc_flags :=

qt_ui_files :=

uic_flags :=

compiler_flags += -isystem/usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem/usr/include/x86_64-linux-gnu/qt5/QtGui -isystem/usr/include/x86_64-linux-gnu/qt5/QtCore -isystem/usr/include/x86_64-linux-gnu/qt5

linker_flags += -lstdc++ -ldl

libs := \
	gui \
	Qt5Widgets \
	Qt5Gui \
	Qt5Core \

lib_version :=

include $(mkf_path)/exe.mk
